### PR TITLE
Use gzip sizes for libraries

### PR DESCRIPTION
**Pull request by ebidel**
R: @GianlucaGuarini

screen shot 2016-02-22 at 11 23 29 am

### CODE REVIEW

**Comment by alexpaluzzi** [comment]
This is a lot more useful! +1

**Comment by abdonrd** [comment]
:+1:

**Comment by GianlucaGuarini** [comment]
well done @ebidel what have you used to calculate the gzip size? What about [this cli](https://github.com/sindresorhus/gzip-size-cli)?

**Comment by GianlucaGuarini** [comment]
@ebidel I am sorry but this comparison is not fair, [react.min.js](https://cdn.jsdelivr.net/react/0.14.7/react.min.js) gzip is only 38.56kb 
screen shot

this means that polymer is still the biggest. Am I missing something here?

**Comment by ebidel** [comment]
I got it from the links on the official site: https://facebook.github.io/react/downloads.html#react-0.14.7-production. 

https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xfa1/t39.3284-6/12624086_185960608428874_474870377_n.js

Not sure what https://cdn.jsdelivr.net/react/0.14.7/react.min.js is.

**Comment by ebidel** [comment]
I used devtools to see the gzipped size for the cdn files. For polymer I used https://github.com/riot/riot/issues/1575#issuecomment-180869792 with:

```
function gz() {
  echo "orig size    (bytes): "
  cat "$1" | wc -c
  echo "gzipped size (bytes): "
  gzip -c "$1" | wc -c
}
```

**Comment by GianlucaGuarini** [comment]
The links you have posted serve react without being "gzipped". The real react.min.js size is 38.56kb and the riot size gzipped is 8.27kb https://cdn.jsdelivr.net/riot/2.3.15/riot.min.js I will update your our site using everywhere the right gzip size

**Comment by GianlucaGuarini** [comment]
@ebidel thanks for the script I will ad it to my `.bash_profile`

**Comment by ebidel** [comment]
Yea, let's be fair to everyone. 

Usually the bottom number in devtools gives you original size, the top gives you gzipped size. Since they differed, I assumed the server was sending gzip'd files.

Running `gz` over https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xfa1/t39.3284-6/12624086_185960608428874_474870377_n.js

locally give me 39581bytes. So that's closer to https://cdn.jsdelivr.net/riot/2.3.15/riot.min.js  :)

**Comment by GianlucaGuarini** [comment]
@ebidel this means that polymer than stays in pole position :)

**Comment by ebidel** [comment]
Yea, I understand. I only care about actual sizes delivered. Not bar comparisons :)

**Comment by GianlucaGuarini** [comment]
:tada: Happily ever after :v:

**Comment by ebidel** [comment]
:book: :dancers: :smile:

**Pull request merged**
