### PR TITLE
Add note for unescaped HTML on japanese doc

### PR DESCRIPTION
**Pull request by tk1024**
#194
This PR translation for Japanese

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
thank you

**Comment by tk1024** [comment]
I checked other translation PR.
Should i send a pull request to `riot:mater`?

**Comment by GianlucaGuarini** [comment]
yes please

**Comment by tk1024** [comment]
@GianlucaGuarini I send new PR. Plaese, check #202

**Pull request merged**
