### PR TITLE
[WIP] Add "Play" pages

### PR DESCRIPTION
**Pull request by cognitom**
live demo riot js

At the first I was thinking about adding pages on [riot/examples](https://github.com/riot/examples) repo. And It would be nice to make it as a Riot SPA itself. But I realise that it could be messy if we try to translate it into other languages...

So now I've changed my mind. I'd like to add "Play" pages to our main site, simply.

- the word "Play" is appropriate?
- need fancy examples like [this](http://codepen.io/dp_lewis/pen/PPqNNV) by @dp-lewis

Any feedback is welcome. Thanks.

### CODE REVIEW

**Comment by MartinMuzatko** [comment]
I love it! Showing riots power not only with words but also with action! I will deliver play examples next week :)

**Comment by dp-lewis** [comment]
I've got a couple of demos I can contribute to this category :)

**Comment by MartinMuzatko** [comment]
I wrote a couple of ```each``` examples:
Object Looping

	```Images``` - Figures : http://codepen.io/MartinMuzatko/pen/yNmpdz
	```Devices``` - Dimensions: http://codepen.io/MartinMuzatko/pen/QbeQdq
	```Table w/ bulk actions``` - http://embed.plnkr.co/u4NaoxYGczha0TVRYQjM/preview

**Comment by tipiirai** [comment]
Looks awesome. I was thinking "Try" but our designer preferred "Play" – so that must be good then!

**Comment by cognitom** [comment]
Hi guys! Thanks for your positive feedbacks :smile: 

I'm now guessing these categories...

- Live demo
- Todo App
- Basics: Timer / Simple router / **Observable** / **Mixin**
- Advanced: Complex router / Table example
- Fun: Clocks
- More

Anyway, could you pls send your example to [here](https://github.com/riot/examples)?
@MartinMuzatko we need a table example.
@dp-lewis I like your clock example!

@gregorypratt I'd like to add your examples. But observable and mixin are difficult to explain it without the code. I'm thinking about how to show them. Is there any idea?

**Comment by MartinMuzatko** [comment]
Oh btw, I wrote a countdown here: https://github.com/MartinMuzatko/counter
I could make it more generic and publish it as plunker.
Table example @cognitom ? please elaborate :)
Creating a table out of a JSON object?

**Comment by MartinMuzatko** [comment]
@cognitom jquery plugins always do a great job of showing when which events are fired. We could write a simple array lister and a kind-of console below to show the user which events are fired/reacted upon when he adds/removes/moves items.

**Comment by cognitom** [comment]
@MartinMuzatko we're gathering the basic examples to [riot/examples](https://github.com/riot/examples) for the convenience of the users. And we'll choose some of them to show on the riotjs.com.
I like [your table example](http://plnkr.co/edit/u4NaoxYGczha0TVRYQjM). It could be nice to share its simplified one, I think.

Basically we should focus on Riot without jQuery, because these are the examples of Riot. But "Riot with jQuery" could be one example. PR of it would be also welcome :-)

**Comment by MartinMuzatko** [comment]
I named jquery not as example together with riot, but their way to show how events work related to their plugins. See http://jqueryui.com/draggable/#events (start invoked 3x, drag invoked 30x, stop invoked 3x)

This does perfectly display how their internal events work, and we could, as I already said: do something similar to showcase the observable. without jquery per se.

About the table example: I'll work on it.

**Comment by cognitom** [comment]
@MartinMuzatko thank you for your explanation. I gotcha :-)
`draggable` looks a nice example and self-explanatory.

**Comment by MartinMuzatko** [comment]
Is there a styleguide to follow when creating examples?
Mainly red (riotstyle) ? minimalistic?

**Comment by cognitom** [comment]
Yeah. Could you check [CONTRIBUTING.md](https://github.com/riot/examples/blob/gh-pages/CONTRIBUTING.md)? And pls see [this example](https://github.com/riot/examples/tree/gh-pages/router-page-switcher).

The dir and files below are for testing:
- test/
- karma.conf.js
- package.json

The file below is for [sending file to Plunker](https://github.com/riot/examples/tree/gh-pages/plunker):
- plunker.json

**Comment by GianlucaGuarini** [comment]
@cognitom isn't time to merge this?

**Comment by cognitom** [comment]
@GianlucaGuarini Yep, let's go!

**Comment by Mouvedia** [comment]
If you add a `{` in the demo it outputs `}`.
e.g. `<li each={ techs }>{ name }{</li>`

Is it a bug?

**Comment by cognitom** [comment]
@Mouvedia maybe not bug. Riot have no spec for incomplete code input.
It depends on where you insert `{`. But I'm not sure why `}` appears...

**Pull request merged**
