### PR TITLE
Riot document Chinese translation. Version 2.2.4

### PR DESCRIPTION
**Pull request by Centaur**
Resend to branch `zh/v2.2.4`

### CODE REVIEW

**Comment by cognitom** [comment]
Great! 謝謝
From now, I'll merge your pr asap, basically without any check :-)
I've learned Chinese when I was a high school student, but that was toooo many years ago.. haha.
Let us know when you'll have done, then we'll be happy to merge this to `master`.

Anyway, thank you for joining us!

**Comment by Centaur** [comment]
All files occured in `/ja` fold, `/_includes/ja` fold, `/_layout/ja.html` have their counterparts in `/zh`, `/_includes/zh` and `/_layout/zh.html`. I have checked the generated `/zh` subsite locally,  including major links between and inside pages.  There may exist some minor typos but yes, I think this is a complete translation. At least as complete as the `/ja` version. I think it's ready for the merge.

**Comment by cognitom** [comment]
@Centaur ok! We'll merge this asap. I'm waiting the response from tipiirai. #24

**Comment by tipiirai** [comment]
So cool: http://riotjs.com/zh/

**Comment by cognitom** [comment]
:tada:

**Pull request merged**
