### PR TITLE
Fr/v2.2.4

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
Looks like I'm done with french translation for 2.2.4 :)

Some commits concern english docs (typos, dead links etc.), I will do a separate PR on master branch for those.

https://github.com/riot/riot.github.io/issues/23

### CODE REVIEW

**Comment by cognitom** [comment]
Awesome!!

**Comment by cognitom** [comment]
@sylvainpolletvillard it looks also include commit on `zh` direcotory. I can update `fr` branch before merging this PR. Is it better to do that?

**Comment by cognitom** [comment]
@sylvainpolletvillard it looks identical to the `master` branch until https://github.com/riot/riot.github.io/commit/c40521b31f3b020ff5fd98d39b18c134372e615f , so I'll update `fr/2.2.4` branch to it. Then, could you `reset` to https://github.com/sylvainpolletvillard/riot.github.io/commit/99617386a1da9e168e47c883b3b37905a25d874a ?
The last commit isn't needed, I think.

**Comment by sylvainpolletvillard** [comment]
Okay, I thought we had to merge with master head revision before PR. 

I force-resetted to https://github.com/sylvainpolletvillard/riot.github.io/commit/99617386a1da9e168e47c883b3b37905a25d874a

@MartinMuzatko you can remove "Merging from master" in your tasks for deutsch translation: https://github.com/riot/riot.github.io/issues/21

**Comment by tipiirai** [comment]
Looks good and thorough. Impressive.

**Comment by cognitom** [comment]
@sylvainpolletvillard perfect! Thanks a lot ;-)

**Comment by cognitom** [comment]
@sylvainpolletvillard just one thing. `api/route.md` is maintained [at riot-route repo](https://github.com/riot/route/tree/master/doc). Could you send PR there, too?
[The separation of an English doc](https://github.com/riot/riot.github.io/pull/40/files#diff-d23e4da1632d5b84c7d9bbf94440ff95L63) is not a so much big problem here. I think we can merge it as is, for this time. (Pls send it separately, for the next time)

**Comment by cognitom** [comment]
OK, now it has been merged into `fr/v2.2.4`.
@sylvainpolletvillard can we merge this into master, too?
We could wait a bit for review from someone, but I can't wait to publish the French docs of Riot :smile_cat:

**Comment by sylvainpolletvillard** [comment]
There are probably still a few typos, and I made arbitrary decisons on how to translate some terms (or not translate them at all) according to what "sounds better" in my opinion. A review is always a good idea, but until you find a reviewer, I think this is already good enough to be merge into master.

Now that Riot is split into several repositories, are we supposed to centralize documentation here or do we scatter the docs on each of the repositories ? I can PR riot-route but if we copy the documentation to several places, is there any long-term plan to maintain consistency between these files ?

**Comment by cognitom** [comment]
Let's go! It's time to publish.

This is the importing command from the repos.
https://github.com/riot/riot.github.io/blob/master/import.sh

We keep our English API document in each sub repo, and keep the docs in other languages in this `riot.github.io` repo.

**Pull request merged**
