### PR TITLE
Fix syntax errors in riot.config.js example

### PR DESCRIPTION
**Pull request by JonathanWolfe**

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
thanks but could you keep the indentation please?

**Comment by JonathanWolfe** [comment]
Like that? Or the `( 'foo' )` too?

**Comment by GianlucaGuarini** [comment]
@JonathanWolfe yeah you are right let's wipe the spaces out

**Comment by JonathanWolfe** [comment]
Removed the spaces in the parens

**Comment by GianlucaGuarini** [comment]
@JonathanWolfe thank you so much!

**Pull request merged**
