### PR TITLE
added: import.sh bash script - for the submodules api.md files

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
I wrote an easy bash script to import the api.md files into the main documentation. @tipiirai @cognitom please have a look at it and check if it works for you

### CODE REVIEW

**Comment by cognitom** [comment]
Looks nice :)
How about `index.md`?

- https://github.com/riot/observable/blob/master/doc/index.md
- https://github.com/riot/router/blob/master/doc/index.md

**Comment by GianlucaGuarini** [comment]
@cognitom in that case I still need to find a good solution to include them into http://riotjs.com/guide/application-design/ I am not even sure they are needed, because only `riot-observable` and `riot-router` are the only submodules having an entry in that page. I will check this later. What's important I think is that any API change must be imported into the main riot documentation

**Comment by cognitom** [comment]
Agreed, it makes sense for me, too.

Then, it could be simpler?

- riot/observable/**doc/index.md** -> riot/observable/**README.md**
- riot/observable/**doc/api.md** -> riot/observable/**doc/index.md**

**Comment by GianlucaGuarini** [comment]
Yes ok it makes sense. I will update the import script and `riot-observable` asap

**Comment by cognitom** [comment]
OK, I'll update `riot-router` soon.

**Comment by GianlucaGuarini** [comment]
@cognitom @tipiirai ok the script got updated we should be ready to merge it

**Comment by tipiirai** [comment]
Already merged so I can play with it. Thanks.

**Comment by tipiirai** [comment]
Were submodules too complex?

**Comment by GianlucaGuarini** [comment]
@tipiirai now we have an issue, on our site http://riotjs.com/api/router/ the doc related to the `riot.route` is wrong, because I prepend `riot` to all the API methods listed [here](https://github.com/riot/router/tree/master/doc). This means that on the site we have `riot.router` instead of `riot.route`.
I think this issue could be fixed just renaming the repo `riot-route` and updating the documentation @cognitom

**Comment by GianlucaGuarini** [comment]
@tipiirai I did not use submodules because the documentation of each riot submodule should be prefixed with `riot.` + `whateversubmodule`, so a simple script was the easiest solution to import and parse correctly all our submodules apis

**Comment by cognitom** [comment]
Yeah, I think so, too:

- `route`: global variable
- `riot.route`: exposed property
- `riot-route`: module name

It looks consistent.

**Comment by GianlucaGuarini** [comment]
ok let's change it and update this repo retriggering `./import.sh` I have no time now :( 
@cognitom you can start by publishing the module on npm

**Comment by cognitom** [comment]
Ok, done. I've already published `riot-route` to npm and Bower.

But, I realized that it has another bug in such a paragraph: 

> Stopping the default riot.router allow the use of a different **riot.**router on your appliaction.

The bold part doesn't make sense.

**Comment by GianlucaGuarini** [comment]
@cognitom I have updated the documentation and the import script in order to prefix just the `route(` `route.` text. The router.md got renamed route.md
cc @tipiirai

**Comment by cognitom** [comment]
Great! Thank you.

**Pull request merged**
