### PR TITLE
ja/v2.3.12

### PR DESCRIPTION
**Pull request by eliot-akira**
This pull request is a continuation of #92, but for the correct branch. For review, there is a checklist on #93.

### CODE REVIEW

**Comment by cognitom** [comment]
@eliot-akira could you solve the conflict?
There're some updates merged from `ja/v2.2.4`.

**Comment by eliot-akira** [comment]
I'm trying to find where the conflicts are - could you tell me how I can find them?

**Comment by eliot-akira** [comment]
OK, I think I got it.

**Comment by cognitom** [comment]
@eliot-akira thanks!
I'm reviewing it. This PR seems including `fr` and `zh` translation, doesn't it?
https://github.com/riot/riot.github.io/pull/94/files

Is it possible to start from `ja/v2.3.12` and cherrypick last five commit of this PR?

**Comment by cognitom** [comment]
Or I'll do that by myself. Maybe later :-)

**Comment by eliot-akira** [comment]
You're right, I see that other past commits got included for some reason. I'll try to sort it out in the next few days. Also, looking at the checklist on #93, some updates are still missing from this PR -- so I'll see if I can make it more complete.

**Pull request closed without merging**
