### PR TITLE
switch font to lato

### PR DESCRIPTION
**Pull request by kfreiman**
issue #64

### CODE REVIEW

**Comment by cognitom** [comment]
@kfreiman can we use thinner weight for the title letters? And some fine tunings.
It would be nice to keep the look and feel of current one (right side).

image

Thoughts? @tipiirai

**Comment by kfreiman** [comment]
@cognitom, here are screenshots with fixed styles:
proxima nova
Lato
Almost no difference!

**Comment by tipiirai** [comment]
Looks great! Just go ahead.

**Comment by cognitom** [comment]
@kfreiman looks much nicer! Thanks.
@tipiirai OK, I'm merging this ;-)

**Comment by kfreiman** [comment]
@tipiirai, @cognitom :thumbsup:

**Comment by tipiirai** [comment]
Thank you guys. Seems like a good font for Riot.

**Pull request merged**
