### PR TITLE
Edited the following lines for grammar & precision

### PR DESCRIPTION
**Pull request by misterhtmlcss**
Line 25. Used possession syntax.
Line 76. Added clarity and brevity.
Line 101. Changed 'above tag' to 'component'.
Line 111.  Added comma, brevity and made it overall more concise. Ex "recognizable when compared to JSX".
..cont. I added this at the end of Line 111. No idea if it's accurate and therefore appropriate.'.....however Riot does allow that HTML and JavaScript can be mixed within expressions.'.

Line 113. stuff is now 'code'.
Line 115. "Just less OF everything with Riot". added 'of' and 'with Riot'.
Line 117. "We believe" not we think.
Line 128. Removed some words and tweaked. PS. "Given the enormous challenge.... " This sentence seems meaningless. Perhaps there is an intended meaning and if so I'd tweak it or remove it.
Line 130. diff'ing. You are referring to diff correct? Then ' is needed then to ensures it's understood without the mental requirement of linking the intent and context to understand it's meaning.
Line 132. Tweaked. Last sentence should or could potentially be removed as it appears excessively verbose or perhaps blended into the second last sentence that relates to it.

Line 137. Shortened and combined with Lin 138.
Line 139.  Riot 'also' comes..... also relates to the preview paragraph and assures the reader of there is equivalence in this area you just praised.
Line 141. brevity again and showed that Riot replaces both Flux and React which isn't clear.
Line 141. 'it's just a library to help you achieve 'the' goal'. What goal? Can we be more specific here? It's a moment to communicate it's value. FYI. All of line 141 confuses me. I'm sure once I know more about Riot I'll get the intent here, but as a newb to the project I felt there was some back and forth. Is Riot like React and Flux? Just like React? This is exacerbated by Line 143's link to RiotControl.

Line 143. changed observable to event emitter for consistency.

Line 171, 176 178. Brevity and precision again. 
Line 180-186. Is this what Polymer does? I would assume so and how is Riot different? Very vague here. Like the writer was tired at this point. I can't help with this part yet, since I'm too new to the project to comment on technical components specific to Riot.

Line 204. Rewrote everything.

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
@misterhtmlcss thank you, we will review it soon!
@tipiirai could you please have a look at this pull request?

**Comment by misterhtmlcss** [comment]
@GianlucaGuarini thank you so much for the positive response. It's my first ever PR, so give me any feedback you feel I can learn from including if my approach was wrong. It's nerve wracking the first (PR) time :)

**Comment by prateekbh** [comment]
@gianlucaguarini did we moved to pronouncing tags as components?

**Comment by GianlucaGuarini** [comment]
@prateekbh no, @misterhtmlcss could you please split your changes in 2 or 3 pull requests please. I would like to merge the grammar issues first and then the rest thanks

**Comment by misterhtmlcss** [comment]
For sure. That'll make it easier for you guys to address different issues.

First thing tomorrow I'll split it up.

**Comment by misterhtmlcss** [comment]
@GianlucaGuarini @prateekbh my day disintegrated. I'll get on soon; don't want to promise again. Sorry for promising and not delivering. It's a priority.

**Comment by misterhtmlcss** [comment]
@GianlucaGuarini @prateekbh hey guys, I'm looking at the PR on GH and it shows all my changes, can you please just go through and comment on the different sections with the GH tools? Separating it out all out literally means I'd have to re-write it at least 2 times (again), which means I've rewritten 3 times at that point.

Please if possible just go through it with the GH tools and make the comments using the GH interface and then I can respond if it's a question for me or someone else; I can tweak whatever pieces you want then and once that's done it can go live.   

Taking it all apart means I have to take down the original and go through it all again, because I can't use the work I did, because mine incorporates everything. Then once I do that, I have to go through it all again and rewrite it as I've done and likely removing some of my grammatical decisions which means redundant effort too.

The least efficient way is for me to rewrite it and would take a considerable effort in addition to my original effort. I accept if this isn't workable on your end and can't really complain, I just wanted to help and saw a way to get started on a project I am really interested in.

**Comment by misterhtmlcss** [comment]
@GianlucaGuarini @prateekbh 
No one is willing to approve or disprove the changes via this very convenient interface on GH? Just click the little + sign next to the changes for comments and I can tweak and finalize?

screen shot 2016-12-10 at 11 14 11 am

**Comment by GianlucaGuarini** [comment]
@misterhtmlcss as I said before your pull request changes many things at once and it will be a lot easier for us to merge and discuss your changes in separate well organized PRs. I doubt we will be able to merge all your changes here. Please follow a sane git workflow https://git-scm.com/book/it/v2/Git-Branching-Branching-Workflows#Topic-Branches it shouldn't be too hard to move your changes in several branches

**Comment by GianlucaGuarini** [comment]
It's a bit sad to close this pull request but there is no activity since 1 year so I am gonna close it for now

**Pull request closed without merging**
